-- Drop tables if they exist (Order matters due to FKs)
DROP TABLE IF EXISTS exam_submissions;
DROP TABLE IF EXISTS exam_questions;
DROP TABLE IF EXISTS exams;
DROP TABLE IF EXISTS question_bank_questions;
DROP TABLE IF EXISTS question_banks;
DROP TABLE IF EXISTS course_selections;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS users;

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'teacher', 'student')),
    email VARCHAR(100) UNIQUE,
    status INT NOT NULL DEFAULT 1,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'User accounts';
COMMENT ON COLUMN users.role IS 'admin, teacher, student';

-- 2. Courses Table
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    teacher_id BIGINT NOT NULL,
    description TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE courses IS 'Courses managed by teachers';

-- 3. Course Selections Table
CREATE TABLE course_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    selection_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_selection_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_selection_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    UNIQUE (student_id, course_id)
);

COMMENT ON TABLE course_selections IS 'Student course enrollments';

-- 4. Questions Table
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('single', 'multiple', 'true_false', 'fill_blank', 'short_answer')),
    options JSONB,
    answer TEXT,
    analysis TEXT,
    difficulty VARCHAR(10) NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    category VARCHAR(50),
    creator_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_questions_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE questions IS 'Question bank';
COMMENT ON COLUMN questions.options IS 'JSON array for options if applicable';

-- 5. Question Banks Table
CREATE TABLE question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    creator_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_banks_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE question_banks IS 'Question banks';

-- 6. Question Bank Questions Relation Table
CREATE TABLE question_bank_questions (
    bank_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    PRIMARY KEY (bank_id, question_id),
    CONSTRAINT fk_qbq_bank FOREIGN KEY (bank_id) REFERENCES question_banks(id) ON DELETE CASCADE,
    CONSTRAINT fk_qbq_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

COMMENT ON TABLE question_bank_questions IS 'Mapping between banks and questions';

-- 7. Exams Table
CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    course_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    duration INT,
    total_score INT NOT NULL DEFAULT 100,
    status INT NOT NULL DEFAULT 0,
    needs_grading BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exams_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_exams_creator FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE exams IS 'Exam definitions';
COMMENT ON COLUMN exams.status IS '0-Draft, 1-Published, 2-Ended';

-- 8. Exam Questions Relation Table
CREATE TABLE exam_questions (
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    score INT NOT NULL DEFAULT 1,
    sequence INT NOT NULL DEFAULT 0,
    PRIMARY KEY (exam_id, question_id),
    CONSTRAINT fk_eq_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    CONSTRAINT fk_eq_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

COMMENT ON TABLE exam_questions IS 'Questions included in an exam';

-- 9. Exam Submissions Table
CREATE TABLE exam_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    answers JSONB,
    submit_detail JSONB,
    submit_score INT,
    status INT NOT NULL DEFAULT 0,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submit_time TIMESTAMP,
    CONSTRAINT fk_submission_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE exam_submissions IS 'Student exam submissions';
COMMENT ON COLUMN exam_submissions.status IS '0-In Progress, 1-Submitted, 2-Graded';

-- ==========================================
-- Sample Data
-- ==========================================

-- Users
INSERT INTO users (username, password, real_name, role, email) VALUES
('admin', 'admin123', 'System Admin', 'admin', 'admin@example.com'),
('teacher1', '123456', 'John Teacher', 'teacher', 'teacher1@example.com'),
('student1', '123456', 'Alice Student', 'student', 'student1@example.com'),
('student2', '123456', 'Bob Student', 'student', 'student2@example.com');

-- Courses
INSERT INTO courses (course_name, teacher_id, description) VALUES
('Mathematics 101', 2, 'Basic Mathematics Course'),
('Physics 101', 2, 'Introduction to Physics');

-- Course Selections
INSERT INTO course_selections (student_id, course_id) VALUES
(3, 1), -- Alice takes Math
(3, 2), -- Alice takes Physics
(4, 1); -- Bob takes Math

-- Questions
INSERT INTO questions (content, type, options, answer, analysis, difficulty, category, creator_id) VALUES
('What is 1 + 1?', 'single', '["1", "2", "3", "4"]', 'B', '1+1=2', 'easy', 'Math', 2),
('Select prime numbers', 'multiple', '["2", "3", "4", "6"]', 'A,B', '2 and 3 are prime', 'medium', 'Math', 2),
('Is the earth flat?', 'true_false', NULL, 'False', 'The earth is round', 'easy', 'General', 2),
('Newton''s First Law states that an object will remain at rest or in uniform motion unless acted upon by a ____.', 'fill_blank', NULL, 'force', 'Basic physics law', 'medium', 'Physics', 2),
('Explain the theory of relativity.', 'short_answer', NULL, 'E=mc^2...', 'Requires detailed explanation', 'hard', 'Physics', 2);

-- Question Banks
INSERT INTO question_banks (name, description, creator_id) VALUES
('Math Bank 1', 'Basic Math Questions', 2),
('Physics Bank 1', 'Physics Questions', 2);

-- Question Bank Questions
INSERT INTO question_bank_questions (bank_id, question_id) VALUES
(1, 1),
(1, 2),
(2, 4),
(2, 5);

-- Exams
INSERT INTO exams (title, description, course_id, creator_id, start_time, end_time, total_score, status, needs_grading) VALUES
('Math Midterm', 'Midterm exam for Math 101', 1, 2, NOW(), NOW() + INTERVAL '1 week', 100, 1, FALSE),
('Physics Final', 'Final exam for Physics 101', 2, 2, NOW(), NOW() + INTERVAL '1 week', 100, 1, TRUE);

-- Exam Questions
INSERT INTO exam_questions (exam_id, question_id, score, sequence) VALUES
(1, 1, 50, 1),
(1, 2, 50, 2),
(2, 4, 40, 1),
(2, 5, 60, 2);

-- Exam Submissions
INSERT INTO exam_submissions (exam_id, user_id, answers, status, start_time) VALUES
(1, 3, '{"1": "B", "2": "A,B"}', 1, NOW());
